config/routes.rb
Rails.application.routes.draw do

# get 'notices/index'
# patch 'notices/update'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  
  post '/usr/search', to: 'usrs#search', as: 'search_usrs'
  post '/video_call/broadcast_data', to: 'video_calls#broadcast_data', as:'data_video_calls'
  post '/video_call/broadcast_signaling', to: 'video_calls#broadcast_signal', as:'signal_video_calls'
  post '/video_call/answer', to: 'video_calls#answer', as:'answer_video_calls'
  get'/video_call/cancel', to: 'video_calls#cancel', as: 'cancel_video_calls'

  get '/upload_avatar', to: 'usrs#upload_avatar', as: 'upload_avatar'
  post '/update_avatar', to: 'usrs#update_avatar', as: 'update_avatar'

  root 'posts#index' 
  resources :posts
  resources :comments
  resources :likes
  resources :usrs
  resources :notices
  resources :follows
  resources :req_friends
  resources :friends
  resources :chats
  resources :rooms
  resources :video_calls
  resources :groups do
    collection do
      post 'add_member'
    end
  end
  namespace :auth do
    resources :signups, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]
  end
  mount Sidekiq::Web, at: '/sidekiq'


  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/group.rb
class Group < ApplicationRecord
  has_one :creator, :class_name => 'User', :foreign_key => 'id', :primary_key => 'creator_id'
  has_many :posts
  has_many :users
  has_and_belongs_to_many :users

  validates :name, presence: true

  before_create :add_code

  def add_code
    self.code = SecureRandom.hex[0..5]
  end

  def add_user id
    GroupsUser.find_or_create_by(user_id: id, group_id: self.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def show
    if(!GroupsUser.find_by(user_id: current_user.id, group_id: params[:id]))
      redirect_to action: 'index'
    else
      @group = Group.find(params[:id])
      @posts = @group.posts.page params[:page]
      @users = @group.users
      @post = Post.new
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = @current_user.groups.new(group_params)
    if @group.save
      @group.add_user(@current_user.id)
      redirect_to @group
    else
      render 'new'
    end
  end

  def add_member
    @group = Group.find_by_code params[:group][:code]
    if(@group)
      @group.add_user(@current_user.id)
      redirect_to @group
    else
      @error = 'Group is not found!'
      redirect_to action: 'index'
    end
  end
  
  private

  def group_params
    params.require(:group).permit(:name)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_friend_list.html.erb
<% users.each do |user| %>
<%= link_to usr_path(user), class:"a-friend" do%>
  <%= image_tag user.image, class: "small-rect-avatar" %>
  <p><%= user.name %></p>
<% end %>
<% end %>

app/views/groups/_group.html.erb
<div class="group-wrap">
  <h5><%= link_to group.name, group_path(group) %></h5>
  <div class="last-active">Last active: <%= group.updated_at %></div>
</div>

app/views/groups/index.html.erb
<%= render "shared/header" %>
<div class="space"></div>
<div class="wrapper-nonposition container">
  <div>
  <div class="other-user-wrapper">
    <div class="other-user-card">
      <div class="title">People you may know</div>
      <div class="other-user-content">
        <%= render partial: 'shared/suggest_users' %>
      </div>
    </div>
  </div>
  </div>
    <div>
    <div class="card-deck-wrapper">
      <div class='row'>
        <div class='col'>
          <%= link_to "New", new_group_path, class: 'btn btn-primary' %>
        </div>

        <div class='col'>
          <%= form_for :group, url: 'groups/add_member', method: 'post', html: {class: 'form-inline' } do |f|%>
            <%= f.label 'Code', html: {for: 'code'}%>
            <%= f.text_field :code, html: {id: 'code', class: 'form-control mx-sm-3'}, class: 'form-control mx-sm-3' %>
            <%= f.submit 'Join', class: 'btn btn-success'%>
          <%end%>
        </div>
      </div>
      <%= render @groups %>
    </div>
    </div>
</div>


<%= render "shared/footer" %>

app/views/groups/new.html.erb
<%= render "shared/header" %>
<div class="space"></div>
<div class="wrapper-nonposition container">
  <div>
  <div class="other-user-wrapper">
    <div class="other-user-card">
      <div class="title">People you may know</div>
      <div class="other-user-content">
        <%= render partial: 'shared/suggest_users' %>
      </div>
    </div>
  </div>
  <div class="shortcut">
    <%= link_to "Groups", groups_path %>
  </div>
  </div>
    <div>
    <div class="card-deck-wrapper">
      <div class='card card-body'>
        <%= form_for @group do |f|%>
          <% if @group.errors.any? %>
          <div class="alert alert-warning" role="alert">
            <% @group.errors.full_messages.each do |message| %>
              <%= message %>
            <%end%>
          </div>
          <%end%>
          <div class='form-group'>
            <%= f.label "Name group" %>
            <%= f.text_field :name, autofocus: true, class: 'form-control' %>
          </div>
          <%= f.submit 'Create', class: 'btn btn-primary', placeholder: 'Enter name group...'%>
        <%end%>
      </div>

    </div>
    </div>
</div>



<%= render "shared/footer" %>

app/views/groups/show.html.erb
<%= render "shared/header" %>
<div class="group-bg-wrap">
  <div class="bg-wrap">
    <%= image_tag "bg3.jpg" %>
  </div>
  <div class="group-name">
    <h3><%= @group.name %></h3>
  </div>
  <div>
    <h6 style='text-align: right; padding-right: 10%;'>Code: <%= @group.code %></h6>
  </div>
</div>
<div class="wrapper-nonposition container">
  <div>
    <div class='information-wrap'>
  <div class="friend-list-wrapper common-card">
    <div class="header-common-card">
      <span><a href="#">Members</a></span>
    </div>
    <div class="friend-list">
      <%= render partial: "friend_list", locals: {users: @users } %>
    </div>
  </div>
    </div>
  </div>
    <div>
        <div class="card-deck-wrapper">
          <div class="new-post-input">
            <div class="ava-text">
              <!-- usr_path(current_user) -->
                  <%= link_to render(partial: 'shared/avatar', locals: {user: current_user}), usr_path(current_user) %>
                  <%= form_for(@post,  remote: true, url: posts_path(@post)) do |f| %>
                    <div class="error-wraper"></div>
                    <%= f.text_area :message, id:"new_post_textarea", placeholder: "Hi #{current_user.name}, what's your mind?", onkeyup:"showPostBtn(this);" %>
                    <div class="result-upload-image" id="preview-images"></div>
                    <!--  <hr> -->
                    <%= f.number_field :group_id, value: @group.id, hidden: true %>
                    
                    <div class="option" >
                    <%= f.file_field :images, id:'post-photo', multiple: true, onchange:"previewImages(this); showPostBtn(this);" %>
                    <%= f.label  for:'post-photo' do %>
                      <%= fa_icon('image')%> Photos
                    <% end %>
                    <%= f.file_field :videos, id:'post-video', multiple: true, onchange:"showPostBtn(this);" %>
                    <%= f.label  for:'post-video' do %>
                      <%= fa_icon('file-video')%> Videos
                    <% end %>
                    <%= f.file_field :files, id:'post-file', multiple: true, onchange:"showPostBtn(this);" %>
                    <%= f.label  for:'post-file' do %>
                      <%= fa_icon('paperclip')%> Attach
                    <% end %>

                    </div>
                    <%= f.submit "Post", class:"btn btn-primary" %>
                  <% end %>


            </div>
          </div>
            <div class=" card-grid">
                <%= render @posts %>
            </div>
        </div>
    </div>
</div>

<div id="paginator">
    <%= paginate @posts, remote: true %>
</div>

<%= render "shared/footer" %>