config/routes.rb
Rails.application.routes.draw do

# get 'notices/index'
# patch 'notices/update'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  
  post '/usr/search', to: 'usrs#search', as: 'search_usrs'
  post '/video_call/broadcast_data', to: 'video_calls#broadcast_data', as:'data_video_calls'
  post '/video_call/broadcast_signaling', to: 'video_calls#broadcast_signal', as:'signal_video_calls'
  post '/video_call/answer', to: 'video_calls#answer', as:'answer_video_calls'
  get'/video_call/cancel', to: 'video_calls#cancel', as: 'cancel_video_calls'

  get '/upload_avatar', to: 'usrs#upload_avatar', as: 'upload_avatar'
  post '/update_avatar', to: 'usrs#update_avatar', as: 'update_avatar'

  root 'posts#index' 
  resources :posts
  resources :comments
  resources :likes
  resources :usrs
  resources :notices
  resources :follows
  resources :req_friends
  resources :friends
  resources :chats
  resources :rooms
  resources :video_calls
  resources :groups do
    collection do
      post 'add_member'
    end
  end
  namespace :auth do
    resources :signups, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]
  end
  mount Sidekiq::Web, at: '/sidekiq'


  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/views/shared/_avatar.html.erb
<%= image_tag(user.image, class:"small-avatar") %>

app/views/shared/_error_messages.html.erb
<div id="error_explanation">
    <div class="alert alert-danger">
        The form contains
        <%= pluralize(@post.errors.count, "error") %>.
    </div>
    <ul>
        <% @post.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
            <% end %>
    </ul>
</div>

app/views/shared/_footer.html.erb
      <div class="chat-icons">
    </div>


    <div class="chats">
        <div class="header-chats" onclick="toggleHeaderChat();">
          <span>Chats (<%= current_user.friends.count %>)</span>
        </div>
        <div class="rooms-list">
          <% current_user.friends.each do |user| %>

            <%= render partial: 'rooms/room', locals: {user: user } %>
          <% end %>
        </div>
    </div>
<div class="chat-tabs-wrap">


</div>

app/views/shared/_header.html.erb
<div class="header">
    <ul class="navb">
        <%= link_to "M", "/", class:"home" %>
        <div class="search-user-wrap">
          <!--  search_usrs_path() -->
        <%= form_for :usr_search, url: search_usrs_path(), method: 'post', remote: true do |f| %>
          <%= f.text_field :name, placeholder: "Search", autocomplete:"off" %>
        <% end %>
        <div class="search-user-result-wrap">
        
        </div>
        </div>
            <div class="user-setting">
              <div class="setting-wrapper">
                <!-- usr_path(current_user) -->
                <%= link_to image_tag(current_user.image, class:"small-avatar"), "#"%>
                    <div class="req-friend-wrapper">

                        <%= button_to req_friend_path(current_user), method: 'patch', remote: true, onclick: "dropdown('#show-notifies, .req-up')" do %>
                            <%= fa_icon 'users' %>
                                <% count = ReqFriend.where(res_user: current_user, seen: false).count %>
                                    <div class="req-count-wrap">
                                        <p class="p-notify req-count">
                                            <%= (count >0) ? count : '' %>
                                        </p>
                                    </div>
                                    <div class="dropdown-content arrow-up req-up"></div>
                                    <% end %>
                                        <div class="dropdown-content all-notifies" id="show-notifies">
                                            <% current_user.req_users.each do |req_user| %>
                                                <%= render 'req_friends/req_friend', user: req_user, c_user: current_user %>
                                                    <% end %>
                                        </div>
                    </div>

                    <div class="message-box-wrap">
                      <!-- rooms_path() -->
                      <%= button_to rooms_path(),  method: 'get', remote: true do %>
            <%= fa_icon 'comments' %>
            <div class="message-count-wrap">
              <!---      <div class="p-notify">*</div> --->
            </div>
            <div class="dropdown-content arrow-up mess-up"></div>
          <% end %>

          <div class="all-messages-wrap">
                        
                    </div>
                    </div>
                    <div class="notify-wrapper">
                      <%= button_to notices_path(),method:'get', onclick:"dropdown('#show-notifyy');", remote: true do %>
                        <%= fa_icon 'bell' %>
                      <% notificationsCount = current_user.notifications.where(isSeen: false).count %>
                      <p class="p-notify"><%= (notificationsCount === 0) ? '' : notificationsCount %></p> 
          <div class="dropdown-content arrow-up">
          </div>
        <% end %>
                  <div class="show-notify dropdown-content" id="show-notifyy">

                  </div>
                    </div>
                    <div class="dropdown-wrapper">
                        <button type="button" class="setting-post-btn" onclick="dropdown('#dropdown-header')"><%= fa_icon "angle-down" %></button>
                        <div class="dropdown-content" id="dropdown-header">
                           <!-- <%= link_to"/", class: "edit-btn", remote: true do %>
                                <%= fa_icon "pencil" %> Edit
                              <% end %> -->
                                        <%= link_to  auth_session_path(current_user), method: :delete, class: "del-btn" do %>
                                            <%= fa_icon "sign-out" %> Sign out
                                                <% end %>
                        </div>
                    </div>
              </div>
            </div>
    </ul>

</div>

app/views/shared/_suggest_users.html.erb
<% temp = 0 %>
<% User.all.each do |user| %>
  <% if current_user != user && current_user.friends.find_by(id: user.id).nil? && current_user.res_users.find_by(id: user.id).nil? && current_user.req_users.find_by(id: user.id).nil? && temp <= 2  %>
    <div class="other-user" id="other-user_<%= user.id %>">
  <%= link_to usr_path(user) do %>
    <%= render(partial: 'shared/avatar', locals: {user: user}) %>
    <p> <%= user.name %></p>
  <% end %>
  <div class="btn-wrap">
    <%= button_to "Add friend", req_friends_path(user), remote: true, method:'post', class:"btn btn-primary" %>
    <button class="btn" onclick="removeById('#other-user_<%= user.id %>');">Delete</button>
  </div>
</div>
<hr>
<% temp = temp + 1 %>
<% end %>
<% end%>