config/routes.rb
Rails.application.routes.draw do

# get 'notices/index'
# patch 'notices/update'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  
  post '/usr/search', to: 'usrs#search', as: 'search_usrs'
  post '/video_call/broadcast_data', to: 'video_calls#broadcast_data', as:'data_video_calls'
  post '/video_call/broadcast_signaling', to: 'video_calls#broadcast_signal', as:'signal_video_calls'
  post '/video_call/answer', to: 'video_calls#answer', as:'answer_video_calls'
  get'/video_call/cancel', to: 'video_calls#cancel', as: 'cancel_video_calls'

  get '/upload_avatar', to: 'usrs#upload_avatar', as: 'upload_avatar'
  post '/update_avatar', to: 'usrs#update_avatar', as: 'update_avatar'

  root 'posts#index' 
  resources :posts
  resources :comments
  resources :likes
  resources :usrs
  resources :notices
  resources :follows
  resources :req_friends
  resources :friends
  resources :chats
  resources :rooms
  resources :video_calls
  resources :groups do
    collection do
      post 'add_member'
    end
  end
  namespace :auth do
    resources :signups, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]
  end
  mount Sidekiq::Web, at: '/sidekiq'


  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/req_friend.rb
class ReqFriend < ApplicationRecord
  belongs_to :req_user, class_name: 'User', optional: true
  belongs_to :res_user, class_name: 'User', optional: true
end

app/controllers/req_friends_controller.rb
class ReqFriendsController < ApplicationController
  def index
    @req_friends = ReqFriend.all
  end
  def create
    @user = User.find_by id: params[:format]
    if @user &&  !(current_user.req_users.find_by id: @user)
      current_user.res_users << @user 
      isFollow = Follow.find_by followee: current_user, follower: @user
      if !isFollow
        Follow.create followee: current_user, follower: @user
      end
    current_user.broadcast_send_req_friend @user
    else
      redirect_to request.referrer
    end
  end

  def update
    @req_friends = ReqFriend.where(res_user: current_user, seen: false).update seen: true
  end

  def destroy
    @user = User.find_by id: params[:id]
    @res_user = ReqFriend.find_by res_user_id: @user, req_user_id: current_user
    @req_user = ReqFriend.find_by req_user_id: @user, res_user_id: current_user

    if @res_user
      @type = 0
      @res_user.destroy
      @req_count = 0
      current_user.broadcast_delete_req_friend @user
    end

    if @req_user
      @type = 1
      @req_user.destroy
      @req_count = ReqFriend.where(res_user_id: current_user, seen: false).count
      current_user.broadcast_delete_req_friend @user
    end
  end
end

app/helpers/req_friends_helper.rb
module ReqFriendsHelper
end

app/views/req_friends/_add_friend.html.erb
<div id="ass-fr-btn">
<%= link_to req_friends_path(user), remote: true, method:'post', class:'btn' do %>
  <%= fa_icon "user-plus" %> Add friend 
<% end %>
</div>

app/views/req_friends/_req_friend.html.erb
<% seen = ReqFriend.find_by(req_user_id: user, res_user_id: c_user).seen %>
<div class="req-friend notify <%= (seen) ? '' : 'active' %> " id="notify-req_<%= user.id %>">
  <%= link_to render(partial: 'shared/avatar', locals:{user: user}), "#" %>
  <p><%= link_to user.name, usr_path(user) %></p>
  <%= link_to "Delete", req_friend_path(user), remote: true, method: "delete", class:"btn btn-delete" %>
  <%= link_to "Confirm", friends_path(user), remote: true, method: "post", class:"btn btn-confirm" %>
  <div class="clearfix"></div>
</div>
<hr>

app/views/req_friends/_requested.html.erb
<div id="ass-fr-btn">
<button class="btn" onclick="dropdown('.dd-req-fri')">
  <%= fa_icon "user-plus" %> Friend request sent
</button>
  <div class="dd-req-fri">
    <%= link_to req_friend_path(user), method:"delete", remote: true, class:"btn" do %>
      <%= fa_icon "trash" %> Delete request
    <% end %>
  </div>
</div>

app/views/req_friends/_respone.html.erb
<div id="ass-fr-btn">
<button class="btn" onclick="dropdown('.dd-req-fri')">
  <%= fa_icon "user-plus" %> Respone to request
</button>
<div class="dd-req-fri">
    <%= link_to friends_path(user), method:"post", remote: true, class: "btn" do %>
      <%= fa_icon "check" %> Confirm request
    <% end %>
    <hr>
    
    <%= link_to req_friend_path(user), remote: true, method:'delete', class:"btn" do %>
      <%= fa_icon "trash" %> Delete request
    <% end %>
  </div>
</div>

app/views/req_friends/create.js.erb
$("#ass-fr-btn").replaceWith("<%= j render 'requested', user: @user %>");
$("#follow-link").replaceWith("<%= j render 'follows/following', follower: @user %>");
$("#other-user_<%= @user.id %>").remove();

app/views/req_friends/destroy.js.erb
$("#ass-fr-btn").replaceWith("<%= j render 'add_friend', user: @user %>");
if (<%= @type %> > 0){
  $("#notify-req_<%= @user.id %>").remove();
  if (<%= @req_count %> > 0){
    $(".req-count-wrap").html("<p class='p-notify req-count' ><%= @req_count %></p>");
  }else{
    $(".req-count-wrap").html("");
  }
}else{

}

app/views/req_friends/index.html.erb
<%= render @req_friends %>

app/views/req_friends/update.js.erb
$(".notify").removeClass("active");
setTimeout(
function()
 {
    $(".req-count").replaceWith("");
 }, 2000);