config/routes.rb
Rails.application.routes.draw do

# get 'notices/index'
# patch 'notices/update'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  
  post '/usr/search', to: 'usrs#search', as: 'search_usrs'
  post '/video_call/broadcast_data', to: 'video_calls#broadcast_data', as:'data_video_calls'
  post '/video_call/broadcast_signaling', to: 'video_calls#broadcast_signal', as:'signal_video_calls'
  post '/video_call/answer', to: 'video_calls#answer', as:'answer_video_calls'
  get'/video_call/cancel', to: 'video_calls#cancel', as: 'cancel_video_calls'

  get '/upload_avatar', to: 'usrs#upload_avatar', as: 'upload_avatar'
  post '/update_avatar', to: 'usrs#update_avatar', as: 'update_avatar'

  root 'posts#index' 
  resources :posts
  resources :comments
  resources :likes
  resources :usrs
  resources :notices
  resources :follows
  resources :req_friends
  resources :friends
  resources :chats
  resources :rooms
  resources :video_calls
  resources :groups do
    collection do
      post 'add_member'
    end
  end
  namespace :auth do
    resources :signups, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]
  end
  mount Sidekiq::Web, at: '/sidekiq'


  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/controllers/usrs_controller.rb
class UsrsController < ApplicationController

  def show
    @user = User.find_by id: params[:id]
    @posts = @user.posts.order(created_at: :desc)
    @like = Like.new
    @comment = Comment.new
    @isFollow = Follow.find_by follower_id: @user, followee_id: current_user
    @isReqFriend = ReqFriend.find_by res_user_id: current_user, req_user_id: @user
    @isResFriend = ReqFriend.find_by req_user_id: current_user, res_user_id: @user
    @isFriend = Friend.find_by current: current_user, friend: @user
  end

  def edit
    @user = User.find_by id: params[:id]
    respond_to do |format|
      format.js
    end
  end

  def update
    @user = User.find_by id: params[:id]
    if @user.update_attributes user_params
      respond_to do |format|
        format.js
      end
    end
  end

  def upload_avatar
     

  end

  def update_avatar
    current_user.avatar.attach(avatar_params[:avatar])
    x = params[:x]
    y = params[:y]
    h = params[:h]
    w = params[:w]

    current_user.urlAvatar(x, y, h, w)
    redirect_to request.referrer
  end

  def search
    @users_result = User.search_user params[:usr_search][:name]
  end

  private
  def user_params
    params.require(:user).permit(:birthday, :gender, :phone, :address)
  end

  def message_params
    params.require(:update_avatar).permit(:message)
  end

  def avatar_params
    params.require(:update_avatar).permit(:avatar)
  end
end

app/views/usrs/_form.html.erb
<%= form_for(@user, :url => usr_path(@user), :method => "patch",  remote: true) do |f| %>
  <div class="error-wraper"></div>
  <%= f.label :birthday %>
  <%= f.date_field :birthday, autofocus: true, class: "form-control", value: f.object.try(:strftime,"%m/%d/%Y") %>
  <%= f.label :gender %>
  <%= f.select :gender, options_for_select([["Select One", ""], "Male", "Famale"]), class:"form-control" %>
  <br>
  <%= f.label :phone %>
  <%= f.number_field :phone, class: "form-control" %>
  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control" %>
  <div class="btn-wrap">
    <%= f.submit "Update", class:"btn btn-primary" %>
    <button class="btn">Cancer</button>
  </div>
<% end %>

app/views/usrs/_form_avatar.html.erb
<div class="card-bg">
  <div class="card-wrapper container">
    <div class="card-titl">Update avatar
      <button onclick="removeElement('.card-bg');"><%= fa_icon 'times' %></button>
    </div>

    <div class="card-bd">
      <%= form_for :update_avatar, url: update_avatar_path(), method:'post' do |f| %>
        <%= f.text_area :message, placeholder:"Add a description..." %>
        <div class="avatar-return">
          <img id="img_prev" src="#" alt="your image" />
        </div>
        <div class="upload-avatar-btn-wrap">
      <div class="new-avatar-wrap">
        <%= f.file_field :avatar, class:"file-input-avatar", id: "new-avatar", onchange:"readURL(this);" %>
        <%= f.hidden_field :x, id:'x', name:'x' %>
        <%= f.hidden_field :y, id:'y', name:'y' %>
        <%= f.hidden_field :w, id:'w', name:'w' %>
        <%= f.hidden_field :h, id:'h', name:'h' %>
        <%= f.label "Select a image...", for:"new-avatar", class:"new-avatar-trigger" %>
      </div>
      <div>
      <button class="btn btn-cancer" onclick="removeElement('.card-bg');">Cancer</button>
      <%= f.submit "Upload", class: "submit-upload-avatar", disabled: true %>
      </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/usrs/_info.html.erb
          <span class="label">Birthday: </span><span class="data"><%= user.birthday %></span>
      <br>
      <span class="label">Gender: </span><span class="data"><%= user.gender %></span>
      <br>
      <span class="label">Phone: </span> <span class="data"><%= user.phone %></span>
      <br>
      <span class="label">Address: </span> <span class="data"><%= user.address %></span>

app/views/usrs/_search_result.html.erb
<div class="dropdown-content search-users-result show">
  <% users.each do |user|  %>
    <%= link_to usr_path(user) do %>
      <%= render partial: 'shared/avatar', locals: {user: user} %>
      <span> <%= user.name %> </span>
    <% end %>
  <% end %>
</div>

app/views/usrs/edit.js.erb
$(".infos, .btn-edit-info-wrap").addClass("hidden");
$(".information").append("<%= j render 'form' %>");

app/views/usrs/search.js.erb
$('.search-user-result-wrap').html('<%= j render "search_result", users: @users_result %>');

app/views/usrs/show.html.erb
<%= render "shared/header" %>
<div class="user-wrap">
  <div class="bg-wrap">
    <%= image_tag "bg3.jpg" %>
  </div>
    <div class="avatar-show">
      <div class="avatar-wrap" onmouseover="showUploadAvatarBtn(this);" onmouseleave="hideUploadAvatarBtn(this);">
        <%= image_tag @user.image %>
        <% if @user === current_user %>
          <%#if false %>
          <%= button_to  upload_avatar_path(), method: 'get', remote: true do %>
            <%= fa_icon 'camera' %>
          <% end %>
        <% end %>
      </div>
      <p class="name"><%= @user.name %></p>
    </div>
  <div class="detail-wrap">
    <div class="information-wrap">
      <div class="action-association common-card">
        <% if @user != current_user %>
          <% if @isFollow %>
            <%= render 'follows/following', follower: @user %>
          <% else %>
            <%= render 'follows/unfollow', unfollower: @user %>
          <% end %>
        <% end  %>

        <% if current_user != @user %>
          
          <% if @isReqFriend %>
            <%= render 'req_friends/respone', user: @user %>
          <% end %>
          <% if @isResFriend %>
            <%= render 'req_friends/requested', user: @user %>
          <% end %>
          <% if !@isReqFriend && !@isResFriend %>
            <% if !@isFriend %>
              <%= render 'req_friends/add_friend', user: @user %>
            <% else %>
              <%= render 'friends/unfriend', user: @user %>
            <% end %>
          <% end %>
        <% end %>
        <div id="message-btn" style="display: none;">
          <%= link_to rooms_path(id: @user.id), remote: true, method:'post', class:'btn' do %>
            <%= fa_icon "comments" %> Message
          <% end %>
        </div>
      </div>

      <div class="information common-card">
        <div class="infos">
          <%= render "info", user: @user %>

        </div>
        <div class="btn-edit-info-wrap">
          <% if @user == current_user %>
            <%= link_to fa_icon("edit"),  edit_usr_path(@user), remote: true, class:"btn" %>
          <% end %>
        </div>
      </div>
      <div class="friend-list-wrapper common-card">
        <div class="header-common-card">
          <span><a href="#">Friends</a></span>
          <span class="mutual-count"><%= @user.get_friend_count %> <%= (@user.get_mutual_friends(current_user).count == 0 || @user === current_user) ? "" : "(#{@user.get_mutual_friends(current_user).count} Mutual)" %></span>
        </div>
        <div class="friend-list">
          <%= render partial: "friend_list", locals: {users: @user.get_friend_list } %>
        </div>
      </div>
       
    </div>
    <div class="card-grid posts-user <%= @posts.count === 0 ? 'no-posts-vailable' : '' %> ">
      <%= (@posts.count === 0) ? "No posts available" : (render @posts) %> 
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/usrs/update.js.erb
$("#edit_user_<%= @user.id %>").remove();
$(".infos").html("<%= j render 'info', user: @user %>");
$(".infos, .btn-edit-info-wrap").removeClass("hidden");

app/views/usrs/upload_avatar.js.erb
$('body').prepend('<%= j render "form_avatar"  %>');